#!/usr/bin/env bash

SH_UTILS="../functions/dataeasy-utils.sh"

if [ ! -f $SH_UTILS ]; then
    echo "$SH_UTILS não encontrado. Abortando." 1>&2
    exit 1
fi

. $SH_UTILS

if [[ "$1" == "-h" ]]; then
    printf "${reset}${underline}Utilização:${reset}\n\n"
    printf "\t${bold}$0${reset} [-s]\n\n"
    printf "${bold}-s${reset}\n"
    printf "\tPosta a imagem criada para o Slack\n\n"
    echo
    exit 0
fi

check_dependency sed # Usuários OSX precisam instalar a versão GNU do sed
check_dependency inkscape

e_de_logo
e_header "Gerando cartaz para DE Talk!"

#######################
# Configs and defaults:
#######################

postToSlack=false

if [[ "$1" == "-s" ]]; then
    postToSlack=true
fi

# Google Drive folder on your machine:
gDriveDir="${HOME}/Google Drive/Eventos/DE Talks"

# Data file:
. ./data

firstName=$(echo $name | cut -f1 -d' ')
lastName=$(echo $name | cut -f2 -d' ')

# Inkscape demands absolute paths:
inputSvg="$(pwd)/Template_DE_Talks.svg"
tempSvg="$(pwd)/temp.svg"
fileName="DE Talks #$num - $title"
pngName="${fileName}.png"
outputPng="$(pwd)/$pngName"

printf "\n\t${reset}${bold}DE Talk #$num:${reset} $title -- $subtitle"
printf "\n\t${reset}${bold}Palestrante:${reset} $name"
printf "\n\t${reset}${bold}Data:${reset} $date às $time"
printf "\n\t${reset}${bold}Keywords:${reset} $keywords"
printf "\n\t${reset}${bold}Público alvo:${reset} $target"
printf "\n\n"

##############
# Gerando PNG:
##############

e_step "Gerando .png"

cp $inputSvg $tempSvg

sed -i'' \
    -e "s#{{firstName}}#$firstName#" \
    -e "s#{{lastName}}#$lastName#" \
    -e "s#{{title}}#$title#" \
    -e "s#{{subtitle}}#$subtitle#" \
    -e "s#{{date}}#$date#" \
    -e "s#{{time}}#$time#" \
    -e "s#{{num}}#$num#" \
    -e "s#{{keywords}}#$keywords#" \
    -e "s#{{target}}#$target#" \
    "$tempSvg"

inkscape $tempSvg -e "$outputPng" &> /dev/null

rm temp.svg

e_check

###################
# Send it to Slack:
###################

if [ "$postToSlack" = true ]; then
    e_step "Enviando para o Slack"

    # channel="C03JUQR77" # canal #sandbox
    channel="C02DJMEUG" # canal #dateasy
    token="xoxp-2460728960-2460728962-8441352294-07fe82"
    message=":mega::speech_balloon: Saudações, @channel! Compareçam e prestigiem!:point_up_2::skin-tone-2::point_up_2::skin-tone-2::point_up_2::skin-tone-2:"

    curl -s -F token="$token" \
        -F file=@"$outputPng" \
        -F filetype="png" \
        -F channels="$channel" \
        -F filename="$pngName" \
        -F title="$fileName" \
        https://slack.com/api/files.upload > /dev/null

    curl -s -F token="$token" \
        -F text="$message" \
        -F username="DE Talks" \
        -F as_user="false" \
        -F channel="$channel" \
        -F icon_emoji=":de_bot:" \
        -F parse="full" \
        https://slack.com/api/chat.postMessage > /dev/null

    e_check
fi

##########################
# Send it to Google Drive:
##########################

e_step "Enviando para o Google Drive (a ser sincronizado)"

finalDir="$gDriveDir/#$num - $title"
mkdir -p "$finalDir"
mv "$outputPng" "$finalDir/"

e_check

e_done

exit 0
