# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae52942ee884a21110c90af02fc34600e190da7a6a543b6a719f9ea3220fe380b27fa55024bfa5f65dedcc8275a733b82b3ccc1242539d93543315c75b39d77d

test:
  secret_key_base: 383e6e5b1476067ff7261fad2b29bffeb6d86b0c745498c4afb229de4ea44320758e9781c564cbc016652928af8b6323235a00f906cc2b0c8589fdbd5b182d3e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
